import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/component/sidebar/sidebar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box } from "@mui/material";
import { LoadingBar, TelegramContextProvider } from "@/hook/use-telegram";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        background: 'white',
        height: '100%'
      }}>
        <AppRouterCacheProvider>
          <TelegramContextProvider>
            <Box sx={{ display: 'flex' }}>
              <Sidebar/>
              <Box
              component="main"
              sx={{ flexGrow: 1, bgcolor: 'background.default' }}
              >
                {children}
              </Box>
            </Box>
            <LoadingBar/>
          </TelegramContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
